### ISSUE TITLE
rock takes only vcf from manta caller ?

### ISSUE THREAD

**Issue by lmanchon** [umccr/rock#12]
is it possible to use other caller than Manta, such as varscan2 ?
thank you --

**Comment by pdiakumis** [comment]
Hi @lmanchon 
Unfortunately no, I have only catered for Manta.

**Comment by lmanchon** [comment]
ok,
and which files from Manta: candidateSV.vcf.gz or diploidSV.vcf
Do i need to convert vcf with convertInversion.py before using rock  ?

than you --

**Comment by pdiakumis** [comment]
Sorry for the delay @lmanchon 
If you check the VCF for columns/fields matching the following, it should be good to go:
https://github.com/pdiakumis/rock/blob/master/R/sv_manta.R#L61

(i.e. make sure it has `INFO/END`, `INFO/MATEID` and `INFO/SVTYPE` under the `INFO` column)
