### ISSUE TITLE
Handle non-bpi VCFs

### ISSUE THREAD

**Issue by pdiakumis** [umccr/rock#3]
BNDs don't get a `INFO/END` field. Need to extract it from the mate's POS. 
See: 
https://github.com/umccr/rock/blob/28aebfd32b13d328b87203e1fa189d81fd6fae27/R/sv_manta.R#L55

**Comment by jlcpEd** [comment]
Thanks for your tool. Can it be used with current Manta VCF files for translocations (BND)?.

I get this for a series of translocation calls in the SAMPLE.link.circos file:

hs2 211289778 211289778 hs6 NA NA color=(102,102,0)
hs2 211322043 211322043 hs3 NA NA color=(102,102,0)
hs2 211330794 211330794 hs7 NA NA color=(102,102,0)

Or "." if I use bcftools. So I can't plot translocations in a circos plot. Manta does not have either INFO/END or INFO/BPI_END in their VCF files. The end coordinate of a translocation is shown in the 5fth column of the VCF file (the ALT column) e.g. [6:23687346[T

**Comment by pdiakumis** [comment]
Thanks for the report!
Hm. That popped up in another case I was looking at, so I'll need to pull it out from the ALT column as you suggest. Will need to come up with a weird regular expression. Will work on it tonight.

**Comment by jlcpEd** [comment]
Thanks.

**Comment by pdiakumis** [comment]
Hi again @jlcpEd.
Very sorry for taking this long to respond - I've been overseas travelling.

I've noticed this issue with files that get processed in some way, which end up with one of the BND mates getting filtered out while its mate remains in the VCF. I have updated the code to filter out these 'orphan' mates.

In any case, the logic of the code works by looking at the POS (second column) of the mate in order to fill in the END values of the BNDs - it doesn't need to look at the ALT column. 
Having said that, there have been a couple cases with weird translocations where this logic didn't quite work, but that was very rare.

I'll close this issue for now, but please let me know if you have a VCF subset which reproduces the issue. I'd love to see what I can do.

Cheers - Peter

**Comment by pdiakumis** [comment]
I finally figured out where the bug was. I simply wasn't selecting the POS column for the BND mate. Hope this fixes your issue.

**Comment by jlcpEd** [comment]
Yes now it works. Thanks very much.
