### ISSUE TITLE
HTTP error 404 while trying to install

### ISSUE THREAD

**Issue by lindakohn** [umccr/rock#4]
Hi,
 I get HTTP error 404 while trying to install:

> devtools::install_github("umccr/rock")
Downloading GitHub repo umccr/rock@master
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 54/60
  Rate limit reset at: 2019-04-01 09:50:59 UTC

**Comment by pdiakumis** [comment]
Oh, thanks for reporting the issue!
I just pushed a fix. Can you re-try now and let me know if you have any issues?

**Comment by lindakohn** [comment]
Worked fine now, thanks!
