### ISSUE TITLE
Run without cnv file

### ISSUE THREAD

**Issue by lindakohn** [umccr/rock#5]
Is it possible to run circos_prep() and plot_circos2() without a cnv file, i.e. only with manta?

**Comment by pdiakumis** [comment]
Good suggestion and good timing, since I'm about to work on that for a project. I'll have a fix up soon.

**Comment by pdiakumis** [comment]
@lindakohn 

I've pushed some code to handle SVs and/or CNVs, depending on what you provide.
Can you try:

```
devtools::install_github("pdiakumis/rock")

# manta <- "/path/to/your/manta/vcf" # or use the below dataset
manta <- system.file("extdata", "HCC2218_manta.vcf", package = "pebbles")
outdir <- "circos_dir"
circos_prep(outdir = outdir, manta = manta)
```

That should write the required circos files to `circos_dir`. Then you can either execute the following from the terminal: 

```
circos -nosvg -conf circos_dir/circos.conf -outputdir circos_dir/ -outputfile circos_sv_only.png
```

... or from within R run:

```
plot_circos(outdir = outdir, name = "sample_A") # note that this isn't called plot_circos2 any more
```

If you have any issues getting `circos` to run, let me know!


![circos_sv](https://user-images.githubusercontent.com/29562861/55398260-dc888a00-5593-11e9-9b81-d572672abfc6.png)

**Comment by lindakohn** [comment]
Great, thank you!
I do however get an error from circos:

      *** CIRCOS ERROR ***

      cwd: /home/lindak/lindak_local_data/Data/WGS_PC/manta/rock

      command: /usr/bin/circos -nosvg -conf circos_dir/circos.conf -outputdir
      circos_dir -outputfile sample_A_circos.png

     CONFIGURATION FILE ERROR

    ...error text from [error/configuration.missing.txt] could not be read...

     If you are having trouble debugging this error, first read the best practices
    tutorial for helpful tips that address many common problems

      http://www.circos.ca/documentation/tutorials/reference/best_practices

      The debugging facility is helpful to figure out what's happening under the
       hood

      http://www.circos.ca/documentation/tutorials/configuration/debugging

      If you're still stumped, get support in the Circos Google Group.

      http://groups.google.com/group/circos-data-visualization

     Please include this error, all your configuration, data files and the version
    of Circos you're running (circos -v).Do not email me directly -- please use
    the group.

     Stack trace:
       at /usr/share/perl5/Circos/Error.pm line 425.
	Circos::Error::fatal_error("configuration", "missing", "circos_dir/circos.conf") called at /usr/share/perl5       
       /Circos/Configuration.pm line 796
	Circos::Configuration::loadconfiguration("circos_dir/circos.conf") called at /usr/share/perl5/Circos.pm                                line 148
  	Circos::run("Circos", "_cwd", "/home/lindak/lindak_local_data/Data/WGS_PC/manta/rock",            "configfile", "circos_dir/circos.conf", "_argv", "-nosvg -conf circos_dir/circos.conf -outputdir circos_dir -ou"..., "outputdir", ...) called at /usr/bin/circos line 538


I've seen threads saying that you need to specify where the 'circos.conf' file is but I haven't managed to get it working...

**Comment by pdiakumis** [comment]
Sorry to hear you're getting errors. Honestly, I've had heaps of trouble trying to get `circos` to work consistently, but it's such a good tool that it's worth persisting.
Today I ended up running it through a docker container and it works flawlessly. If you know what docker is, you can try going through https://github.com/alexcoppe/bio-dockers/tree/master/circos

Let me know how you go and if you need help setting that up - you'd need to install Docker e.g. for Mac [this is the link](https://hub.docker.com/editions/community/docker-ce-desktop-mac).

**Comment by pdiakumis** [comment]
I'm closing this since it looks to be related to circos, not rock. I tend to generate all config files via rock and run circos via a docker container.
